### ISSUE TITLE
PyPI publishing setup for GHA

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/magicbus#14]
@jaraco since I don't have access to this package on PyPI, could you please [add a `PYPI_TOKEN` secret in this repo settings](https://github.com/cherrypy/magicbus/settings/secrets/actions/new)?
Or just add me to the package maintainers on PyPI and then I can do it myself. The GHA setup that needs it is https://github.com/cherrypy/magicbus/pull/13.

**Comment by jaraco** [comment]
I've done both.
